### ISSUE TITLE
support play video use another video player

### ISSUE THREAD

**Issue by hhsw2015** [bharathganji/pikpak-plus#35]
support play video use native video player ,  like iina  potplayer etc

**Comment by bharathganji** [comment]
Hi @hhsw2015 ,

Currently u can copy stream link and use your native player to stream video

Eg: in vlc media player, u can use the "new stream" option and paste the copied link. Video will start playing.

Anyway I will try to provide dedicated xplay with another app" option just like pikpak.

**Comment by bharathganji** [comment]
https://github.com/bharathganji/pikpak-plus/pull/41
