### ISSUE TITLE
[BUG] batch add links not working

### ISSUE THREAD

**Issue by hhsw2015** [bharathganji/pikpak-plus#42]
i add 2 magnet links

magnet:?xt=urn:btih:BDBC44DA9CAE52C424AB9FFB7E7733A3E85085C0
magnet:?xt=urn:btih:8DD1AAFEEF0E4DA767624479494262DE36184C91

but there is only one task be downloaed

**Comment by bharathganji** [comment]
fixed https://github.com/bharathganji/pikpak-plus/pull/43
