### ISSUE TITLE
can not download if delete the user data dir in pikpak netdisk

### ISSUE THREAD

**Issue by hhsw2015** [bharathganji/pikpak-plus#44]
if i delete the user dir for some user,  then the use  can not use the pikpak-plus anymore

if the user's data dir be deleted for some reason, when the user login the pikpak-plus, the data dir should be recreate auto
and 
pikpak_data 's dircetory_id need be update auto

**Comment by bharathganji** [comment]
Yes, u cannot use pikpak plus, if u delete directory..

I recommend not deleting the directory in pikpak.

To resolve this 

Recreate a folder and update that id into supabase

If still facing issues, just delete user authentication and all its user data from supabase and use signup again
Or
Create a new user.

Note : It's not possible to create same directory id again i. Pikpak, it's not in our hands
