### ISSUE TITLE
support poster wall

### ISSUE THREAD

**Issue by hhsw2015** [bharathganji/pikpak-plus#54]
there is only folder view for file now, 
can support poster wall view like emby
use pikpak api to get video's thumbnail

**Comment by hhsw2015** [comment]
just like gallery image wall, and scroll down to view more item, click one item to play video or view image

**Comment by hhsw2015** [comment]
here is a ui demo : [https://same.energy/search?q=tree](https://same.energy/search?q=tree)

**Comment by hhsw2015** [comment]
here is a demo project:  [Kyoo](https://github.com/zoriya/Kyoo)

**Comment by bharathganji** [comment]
HI @hhsw2015 , 

i've seached for ways to achieve this, but pikpak directly not providing such api's for us to achieve this.

i found a simple way to achieve this with media management applications + webdav. and made a video - https://youtu.be/o7I87uHANcQ

same can be done using jellyfin/emby but some extra process we need to follow which will be complicated and diviated from this project

**Comment by bharathganji** [comment]
I've also implemented poster view for small images

Pls check below video

https://file.io/RrBAQKAGhm1P
