### ISSUE TITLE
Site will be down till solution found to fix captcha issue

### ISSUE THREAD

**Issue by bharathganji** [bharathganji/pikpak-plus#62]
an issue was submitted to original pikpakApi repo
will wait till issue resolved and site will be down..

link - https://github.com/Quan666/PikPakAPI/issues/29

**Comment by bharathganji** [comment]
https://github.com/bharathganji/pikpak-plus/pull/63

fixed issue, site will be resumed

**Comment by Quan666** [comment]
Try this https://github.com/Quan666/PikPakAPI/commit/201e6e738b1e7133833d9fac02fc965abbb55a21
