### ISSUE TITLE
Error during sign in (apk version)

### ISSUE THREAD

**Issue by arcevan** [bharathganji/pikpak-plus#66]
![Screenshot_20240908-040803_pikpak-plus](https://github.com/user-attachments/assets/508de823-984a-4b67-a069-bc0cdab2e29a)

**Comment by badboifx** [comment]
Error while trying to login

**Comment by bharathganji** [comment]
The site was down on sep 8 for almost 48 hours, due to pikpak restriction.

Issue resolved now.

**Comment by bharathganji** [comment]
This was old version of website could u pls update to new or use website 

Present days app was not Fully aligned with website 

> ![Screenshot_20240908-040803_pikpak-plus](https://github.com/user-attachments/assets/508de823-984a-4b67-a069-bc0cdab2e29a)
>
